data:extend({
    {
        name = 'adaptive-movement-speed-global-enabled',
        type = 'bool-setting',
        setting_type = 'runtime-global',
        order = 'a',
        default_value = true,
    },
    {
        name = 'adaptive-movement-speed-global-maximum-speed',
        type = 'double-setting',
        setting_type = 'runtime-global',
        order = 'b',
        default_value = 500,
        minimum_value = 100,
        maximum_value = 100000,
    },
    {
        name = 'adaptive-movement-speed-global-disable-upon-taking-damage',
        type = 'double-setting',
        setting_type = 'runtime-global',
        order = 'c',
        default_value = 4,
        minimum_value = 0,
        maximum_value = 60,
    },
    {
        name = 'adaptive-movement-speed-enabled',
        type = 'bool-setting',
        setting_type = 'runtime-per-user',
        order = 'a',
        default_value = true,
    },
    {
        name = 'adaptive-movement-speed-base-speed',
        type = 'double-setting',
        setting_type = 'runtime-per-user',
        order = 'b',
        default_value = 100,
        minimum_value = 10,
        maximum_value = 10000,
    },
    {
        name = 'adaptive-movement-speed-maximum-speed',
        type = 'double-setting',
        setting_type = 'runtime-per-user',
        order = 'c',
        default_value = 200,
        minimum_value = 20,
        maximum_value = 100000,
    },
    {
        name = 'adaptive-movement-speed-speed-up-time',
        type = 'double-setting',
        setting_type = 'runtime-per-user',
        order = 'd',
        default_value = 5,
        minimum_value = 0.1,
        maximum_value = 60,
    },
    {
        name = 'adaptive-movement-speed-cool-down-time',
        type = 'double-setting',
        setting_type = 'runtime-per-user',
        order = 'e',
        default_value = 2,
        minimum_value = 0.1,
        maximum_value = 60,
    },
})
